WITH SETOR AS (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA),

ENDE AS (SELECT CLICODIGO,ZODESCRICAO FROM ENDCLI LEFT JOIN SETOR ON ENDCLI.ZOCODIGO=SETOR.ZOCODIGO WHERE ENDFAT='S'),

CLI1 AS (SELECT DISTINCT CL.CLICODIGO,TBPCODIGO,ZODESCRICAO FROM CLITBP CL 
LEFT JOIN ENDE ON CL.CLICODIGO=ENDE.CLICODIGO),

CLI2 AS (SELECT DISTINCT CL.CLICODIGO,TBPCODIGO,ZODESCRICAO FROM CLITBPCOMB CL 
LEFT JOIN ENDE ON CL.CLICODIGO=ENDE.CLICODIGO)

SELECT TA.TBPCODIGO COD_TABELA,CLICODIGO,TBPDESCRICAO DESCRICAO,TBPDTVALIDADE VALIDADE,
ZODESCRICAO FROM TABPRECO TA
LEFT JOIN CLI1 C1 ON TA.TBPCODIGO=C1.TBPCODIGO
WHERE TBPSITUACAO='A' AND TBPDTVALIDADE >='TODAY' AND 
TBPDESCRICAO NOT LIKE '%PROMO DO MES%' AND TBPTABCOMB='N' UNION

SELECT TA.TBPCODIGO COD_TABELA,CLICODIGO,TBPDESCRICAO DESCRICAO,TBPDTVALIDADE VALIDADE,
ZODESCRICAO FROM TABPRECO TA
LEFT JOIN CLI2 C2 ON TA.TBPCODIGO=C2.TBPCODIGO
WHERE TBPSITUACAO='A' AND TBPDTVALIDADE >='TODAY' AND 
TBPDESCRICAO NOT LIKE '%PROMO DO MES%' AND TBPTABCOMB='S'