WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISCODIGO IN ('5.101','5.102','5.117','5.91V','6.101','6.102','6.117','6.91V')),

PED AS (SELECT PEDID.ID_PEDIDO FROM PEDID INNER JOIN FIS ON FIS.FISCODIGO=PEDID.FISCODIGO1 
        WHERE PEDDTEMIS BETWEEN '01.06.2023' AND 'TODAY' AND PEDSITPED<>'C'),
          
          PD AS (SELECT PDPRD.ID_PEDIDO,PROCODIGO,PDPDESCRICAO FROM PDPRD 
                 INNER JOIN PED ON PDPRD.ID_PEDIDO=PED.ID_PEDIDO),
        
        PEDIDOBSER AS (SELECT PEDID.ID_PEDIDO FROM PEDID 
                       INNER JOIN PED ON PEDID.ID_PEDIDO=PED.ID_PEDIDO 
                       WHERE
                       (PEDOBSER LIKE '%%CUPOM%%' OR PEDOBSER LIKE '%%cupom%%' OR PEDOBSER LIKE '%%PROMO%%'OR PEDOBSER LIKE '%%promo%%'OR PEDOBSER LIKE '%%PROMOCAO%%' OR PEDOBSER LIKE '%%promocao%%' OR PEDOBSER LIKE '%%SEGUNDO%%' OR PEDOBSER LIKE '%%segundo%%' OR PEDOBSER LIKE '%%PRIMEIRO%%' OR PEDOBSER LIKE '%%primeiro%%' OR PEDOBSER LIKE '%%1.PAR%%' OR PEDOBSER LIKE '%%1.par%%' or PEDOBSER LIKE '%%2.PAR%%' or PEDOBSER LIKE '%%2.par%%' OR PEDOBSER LIKE '%%1 PAR%%' OR PEDOBSER LIKE '%%2 PAR%%' OR PEDOBSER LIKE '%%1 par%%' OR PEDOBSER LIKE '%%2 par%%'OR PEDOBSER LIKE '%%EM DOBRO%%' OR PEDOBSER LIKE '%%em dobro%%' OR PEDOBSER LIKE '%%MEU%%' OR PEDOBSER LIKE '%%meu%%' OR PEDOBSER LIKE '%%dose dupla%%' OR PEDOBSER LIKE '%%MINHA PRIMEIRA%%' OR PEDOBSER LIKE '%%GRATIS%%' OR PEDOBSER LIKE '%%gratis%%' OR PEDOBSER LIKE '%%CUPON%%' OR PEDOBSER LIKE '%%cupon%%' OR PEDOBSER LIKE '%%2º Par%%' OR PEDOBSER LIKE '%%1º VL%%' OR PEDOBSER LIKE '%VARILUX%')),
        
        PDPAP AS (SELECT PDPRD.ID_PEDIDO FROM PDPRD 
                  INNER JOIN PED ON PDPRD.ID_PEDIDO=PED.ID_PEDIDO WHERE PROCODIGO='PAP'),
        
        PDPROMO AS (SELECT PDPRD.ID_PEDIDO FROM PDPRD 
                    INNER JOIN PED ON PDPRD.ID_PEDIDO=PED.ID_PEDIDO WHERE PROCODIGO='PROMO'),
        
        CLI AS (SELECT CLICODIGO,CLIRAZSOCIAL FROM CLIEN WHERE CLICLIENTE='S'),
        
        PDPPAR AS (SELECT ID_PEDIDORIGINAL FROM PEDIDPROMO
                   INNER JOIN PED ON PEDIDPROMO.ID_PEDIDORIGINAL=PED.ID_PEDIDO),
        
        PDSPAR AS (SELECT ID_PEDIDPROMOCAO FROM PEDIDPROMO
                   INNER JOIN PED ON PEDIDPROMO.ID_PEDIDPROMOCAO=PED.ID_PEDIDO),
        
        NFCANCEL AS (SELECT NFCODIGO,NFSIT FROM NOTAS WHERE NFDTEMIS >='01.06.2023' AND NFSIT<>'C'),
                       
                       NF AS (SELECT PDNF.ID_PEDIDO,PDNF.NFCODIGO FROM PDNF 
                              INNER JOIN PED ON PDNF.ID_PEDIDO=PED.ID_PEDIDO
                              INNER JOIN NFCANCEL ON PDNF.NFCODIGO=NFCANCEL.NFCODIGO
                       )
                     
                     SELECT PEDID.ID_PEDIDO,
                     PEDDTEMIS DATA_EMISSAO,
                     PEDID.CLICODIGO COD_CLIENTE,
                     CLIRAZSOCIAL RAZAO_SOCIAL,
                     IIF(PDPAP.ID_PEDIDO IS NULL,NULL,'S') PAP,
                     IIF(PDPROMO.ID_PEDIDO IS NULL,NULL,'S') PROMO,
                     CAST(PEDOBSER AS VARCHAR(4096)) AS OBSER,
                     FISCODIGO1 CFOP,
                     NFCODIGO NOTA 
                     FROM
                     PEDID
                     INNER JOIN PED ON PEDID.ID_PEDIDO=PED.ID_PEDIDO
                     INNER JOIN PEDIDOBSER ON PEDID.ID_PEDIDO=PEDIDOBSER.ID_PEDIDO
                     LEFT JOIN PD ON PEDID.ID_PEDIDO=PD.ID_PEDIDO
                     LEFT JOIN PDPAP ON PEDID.ID_PEDIDO=PDPAP.ID_PEDIDO
                     LEFT JOIN PDPROMO ON PEDID.ID_PEDIDO=PDPROMO.ID_PEDIDO 
                     LEFT JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO 
                     LEFT OUTER JOIN PDPPAR ON PEDID.ID_PEDIDO=PDPPAR.ID_PEDIDORIGINAL 
                     LEFT OUTER JOIN PDSPAR ON PEDID.ID_PEDIDO=PDSPAR.ID_PEDIDPROMOCAO
                     LEFT JOIN NF ON PEDID.ID_PEDIDO=NF.ID_PEDIDO
                     WHERE PDPPAR.ID_PEDIDORIGINAL IS NULL AND PDSPAR.ID_PEDIDPROMOCAO IS NULL
                     UNION
                     
                     SELECT PEDID.ID_PEDIDO,
                     PEDDTEMIS DATA_EMISSAO,
                     PEDID.CLICODIGO COD_CLIENTE,
                     CLIRAZSOCIAL RAZAO_SOCIAL,
                     IIF(PDPAP.ID_PEDIDO IS NULL,NULL,'S') PAP,
                     IIF(PDPROMO.ID_PEDIDO IS NULL,NULL,'S') PROMO,
                     CAST(PEDOBSER AS VARCHAR(4096)) AS OBSER,
                     FISCODIGO1 CFOP,
                     NFCODIGO NOTA 
                     FROM
                     PEDID
                     INNER JOIN PED ON PEDID.ID_PEDIDO=PED.ID_PEDIDO
                     INNER JOIN PDPAP ON PEDID.ID_PEDIDO=PDPAP.ID_PEDIDO
                     LEFT JOIN PDPROMO ON PEDID.ID_PEDIDO=PDPROMO.ID_PEDIDO
                     LEFT JOIN PD ON PEDID.ID_PEDIDO=PD.ID_PEDIDO
                     LEFT JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO 
                     LEFT OUTER JOIN PDPPAR ON PEDID.ID_PEDIDO=PDPPAR.ID_PEDIDORIGINAL
                     LEFT OUTER JOIN PDSPAR ON PEDID.ID_PEDIDO=PDSPAR.ID_PEDIDPROMOCAO
                     LEFT JOIN NF ON PEDID.ID_PEDIDO=NF.ID_PEDIDO
                     WHERE PDPPAR.ID_PEDIDORIGINAL IS NULL AND PDSPAR.ID_PEDIDPROMOCAO IS NULL UNION
                     
                     SELECT PEDID.ID_PEDIDO,
                     PEDDTEMIS DATA_EMISSAO,
                     PEDID.CLICODIGO COD_CLIENTE,
                     CLIRAZSOCIAL RAZAO_SOCIAL,
                     IIF(PDPAP.ID_PEDIDO IS NULL,NULL,'S') PAP,
                     IIF(PDPROMO.ID_PEDIDO IS NULL,NULL,'S') PROMO,
                     CAST(PEDOBSER AS VARCHAR(4096)) AS OBSER,
                     FISCODIGO1 CFOP,
                     NFCODIGO NOTA 
                     FROM
                     PEDID
                     INNER JOIN PED ON PEDID.ID_PEDIDO=PED.ID_PEDIDO
                     INNER JOIN PDPROMO ON PEDID.ID_PEDIDO=PDPROMO.ID_PEDIDO
                     LEFT JOIN PDPAP ON PEDID.ID_PEDIDO=PDPAP.ID_PEDIDO
                     LEFT JOIN PD ON PEDID.ID_PEDIDO=PD.ID_PEDIDO
                     LEFT JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
                     LEFT OUTER JOIN PDPPAR ON PEDID.ID_PEDIDO=PDPPAR.ID_PEDIDORIGINAL
                     LEFT OUTER JOIN PDSPAR ON PEDID.ID_PEDIDO=PDSPAR.ID_PEDIDPROMOCAO
                     LEFT JOIN NF ON PEDID.ID_PEDIDO=NF.ID_PEDIDO
                     WHERE PDPPAR.ID_PEDIDORIGINAL IS NULL AND PDSPAR.ID_PEDIDPROMOCAO IS NULL