WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT CLICODIGO,
                ID_PEDIDO,
                 CAST(PEDOBSER AS VARCHAR (4096)) AS PEDOBSER,
                 PEDDTEMIS,
                  PEDVRTOTAL,
                  POCCODIGO FROM PEDID P
     WHERE PEDSITPED <> 'C'
     AND PEDDTEMIS BETWEEN '01.12.2022' AND '31.03.2023'),
     
PROMO AS (SELECT ID_PEDIDO,PIPPROMOCAO,PIPPAR,PIPVOUCHER,PIPVRPEDIDO FROM PDINFOPROMO)
     
SELECT 
  PD.ID_PEDIDO,
   PEDDTEMIS DATA_EMISSAO,
    PEDOBSER,
     P.CLICODIGO COD_CLIENTE,
     CLIRAZSOCIAL RAZAO_SOCIAL,
     PROCODIGO COD_PRODUTO,
      PDPDESCRICAO PROD_DESCRICAO,
       PEDVRTOTAL VALOR_TOTAL,
        PIPVOUCHER VOUCHER,
        '' PEDIDO_RELACIONADO,
              CASE
               WHEN PIPPAR=1 THEN 'PEDIDO_1' 
               WHEN PIPPAR=2 THEN 'PEDIDO 2'
               ELSE NULL END PAR,
               POCCODIGO ORIGEM_CAPTACAO,
                PDPQTDADE QTD

    FROM PDPRD PD
    INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    LEFT JOIN FIS F ON PD.FISCODIGO=F.FISCODIGO
    INNER JOIN PROMO PR ON P.ID_PEDIDO=PR.ID_PEDIDO
    LEFT JOIN (SELECT CLICODIGO,CLIRAZSOCIAL FROM CLIEN WHERE CLICLIENTE='S')A ON P.CLICODIGO=A.CLICODIGO