
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')
),

NF AS (SELECT EMPCODIGO,CLICODIGO,NFDTEMIS,NT.NFCODIGO,NFLCFINANC FROM NOTAS NT
WHERE NFDTEMIS BETWEEN @#DATE#DATA_INCIO@ and  @#DATE#DATA_FIM@
AND NFSIT = 'N'
),

PEDNF AS (SELECT DISTINCT P.NFCODIGO,P.ID_PEDIDO FROM PDNF P
                    INNER JOIN NF N ON N.NFCODIGO=P.NFCODIGO),

PED AS 
  (SELECT P.ID_PEDIDO
    FROM PEDID P
    INNER JOIN PEDNF F ON P.ID_PEDIDO=F.ID_PEDIDO),


CALC AS(SELECT 
NP.EMPCODIGO,
NP.NFCODIGO,
ID_PEDIDO,
NP.FISCODIGO,
CLICODIGO,
NFDTEMIS, 
NFPVRCONTABIL,
NFPVRPIS,
NFPVRICMS,
NFPVRCOFINS,
CAST(SUM(NFPUNITLIQUIDO*NFPQTDADE)  AS NUMERIC(18,2)) VRVENDA,
CAST(SUM(NFPVRFRETE)AS NUMERIC(18,2)) FRETE,
(CAST(SUM(NFPUNITLIQUIDO*NFPQTDADE)  AS NUMERIC(18,2)) + CAST(SUM(NFPVRFRETE)AS NUMERIC(18,2))) VRTOTAL,
(CAST(SUM(NFPUNITLIQUIDO*NFPQTDADE)  AS NUMERIC(18,2)) + CAST(SUM(NFPVRFRETE)AS NUMERIC(18,2))) - 
CAST(SUM(NFPVRICMS) AS NUMERIC(18,2)) - 
CAST(SUM(NFPVRPIS) AS NUMERIC(18,2)) -
CAST(SUM(NFPVRCOFINS) AS NUMERIC(18,2)) VRLIQUIDO

FROM NFPRO NP
INNER JOIN NF ON NP.NFCODIGO=NF.NFCODIGO AND NP.EMPCODIGO=NF.EMPCODIGO
INNER JOIN FIS ON NP.FISCODIGO=FIS.FISCODIGO
LEFT JOIN PEDNF PE ON NP.NFCODIGO=PE.NFCODIGO
WHERE
(NP.NFPLCFINAN = 'S' AND NF.NFLCFINANC <> 'L' OR  NP.NFPLCFINAN = 'N' OR  NF.NFLCFINANC = 'L' AND NP.NFPLCFINAN = 'S' )
GROUP BY 1,2,3,4,5,6,7,8,9,10
)


SELECT
NFDTEMIS,
TRIM(NFCODIGO) NFCODIGO,
TRIM(ID_PEDIDO) ID_PEDIDO,
EMPCODIGO,
SUM(VRVENDA) VRVENDA
FROM CALC C
GROUP BY 1,2,3




