-- PEDIDOS AGUARDANDO CONFERENCIA FINAL
WITH PED AS (
SELECT 
ID_PEDIDO
FROM PEDID
WHERE
PEDPZETGSIS
BETWEEN
@#DATE#DATA_PREVISAO_ENTREGA_SISTEMA_INICIO@ and  @#DATE#DATA_PREVISAO_ENTREGA_SISTEMA_FIM@),

CONF AS (
SELECT 
PR.ID_PEDIDO,
ALXCODIGO,
PDRCONCLUIDO,
PDRORDEM,
PDRORDEM-1 PDRANTERIOR
FROM
PEDROTEIRO PR
INNER JOIN PED P ON PR.ID_PEDIDO=P.ID_PEDIDO
WHERE EMPCODIGO=1 AND ALXCODIGO=52 AND PDRCONCLUIDO<>'S'),

ANT AS( 
SELECT 
PR.ID_PEDIDO,
PR.ALXCODIGO,
PR.PDRCONCLUIDO,
PR.PDRORDEM
FROM
PEDROTEIRO PR
INNER JOIN PED P ON PR.ID_PEDIDO=P.ID_PEDIDO
INNER JOIN CONF C ON PR.ID_PEDIDO=C.ID_PEDIDO AND C.PDRANTERIOR=PR.PDRORDEM
WHERE EMPCODIGO=1 AND PR.PDRCONCLUIDO='S')

 
SELECT 
DISTINCT P.ID_PEDIDO
FROM
PEDROTEIRO P
INNER JOIN CONF C ON P.ID_PEDIDO=C.ID_PEDIDO 
INNER JOIN ANT A ON P.ID_PEDIDO=A.ID_PEDIDO 
WHERE EMPCODIGO=1
